# Generated by Django 5.1 on 2024-08-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('years_of_exp', models.FloatField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('current_salary', models.PositiveIntegerField()),
                ('expected_salary', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='applied', max_length=15)),
            ],
        ),
    ]
